#Kullanıcının girdiği sayının asal olup olmadığını belirle.

# num=int(input("Bir sayı(pozitif) girin:"))

# for x in range(2,num):
#     if num%x!=0:
#            asal=True
#            break
# if asal:
#         print("Sayınız asaldır ")
# else:
#         print("Sayınız asal degildir")








# num1=int(input("bir sayı giriniz:"))
# Asal=True
# for i in range(2,num1):
#     if num1%i==0:
#         Asal=False
#         break
             
# if(Asal):
#     print("Sayınız asaldır...")
# else:
#     print("Sayınız asal degill!!..")
        
