
import turtle
t =turtle.Turtle()
w = turtle.Screen()
w.title("Cumhuriyetimizin 100. Yılı")
w.setup (width=600,height=400)
w.bgcolor("red")
t.up()
t.goto(-100,-100)
t.color("white")
t.begin_fill()
t.circle(120)
t.end_fill()
t.goto(-70,-80)
t.color("red")
t.begin_fill()
t.circle(100)
t.end_fill()
t.goto(60,40)
t.fillcolor("white")
t.begin_fill()
for i in range(5):
    t.forward(50)
    t.right(144)
    t.forward(50)
    t.right(-72)
t.end_fill()
t.goto(-400,-190)
t.color("white")
t.write("MEHMET ŞÜKRÜ AYBAR",font=("Articulate",40,"bold")) 
t.goto(-400,-290)
t.color("white")
t.write("TÜRKİYE",font=("Articulate",40,"bold"))
t.goto(-999,-0)
w.exitonclick()