#                                                        FAKTORYEL KODU
# while(True):                                        
#     num=int(input("Tam sayı giriniz:"))
#     if num>0:
#         factor=1
#         for i in range(1,num+1):  
#              factor*=i        
#     print("Sayınızın faktoryeli={}".format(factor))
#     if num<0:
#         print("Negatif sayılarda işlem yapılmıyor")
#         continue

        